# Search algorithms 

Practice the fundamentals of:
* Search algorithms
* Graph algorithms
* Dynamic programming

In [1]:
# Import libraries
import numpy as np 
from typing import Optional
import copy

## Strings and Arrrays

### Two pointers

In [7]:
# Example 1: Given a string s, return true if it is a palindrome, false otherwise.

class PalindromeSolution:
    def is_palindrome(self, s):
        for i in range(0,len(s)):
            if s[i] != s[-(i+1)]:
                return False
        return True

palindrome_example_1 = 'trial'
palindrome_example_2 = 'noon'

palindrome_solution = PalindromeSolution()
print(palindrome_solution.is_palindrome(palindrome_example_1))
print(palindrome_solution.is_palindrome(palindrome_example_2))

False
True


In [19]:
# Example 2: Given a sorted array of unique integers and a target integer, 
# return true if there exists a pair of numbers that sum to target, false otherwise. 

# For example, given nums = [1, 2, 4, 6, 8, 9, 14, 15] and target = 13, return true because 4 + 9 = 13.

class PairSumSolution:
    def contains_pair_matching_target_sum(self, sorted_array, target_sum):
        index_end = len(sorted_array) - 1
        i = 0
        j = index_end
        while i <= index_end and j >= 0: # using (left < right) instead avoids duplicate work
            current_sum = sorted_array[i] + sorted_array[j]
            if current_sum == target_sum:
                return True
            if current_sum < target_sum:
                i += 1
            if current_sum > target_sum:
                j -= 1
        
        return False
            
            
array_example = [1, 2, 4, 6, 8, 9, 14, 15]
target_example = 13

pair_sum_solution = PairSumSolution()
print(pair_sum_solution.contains_pair_matching_target_sum(array_example, target_example))


True


### Sorting

In [17]:
# Example 3: Given two sorted integer arrays arr1 and arr2, 
# return a new array that combines both of them and is also sorted.

class MergeSortedSolution:
    def merge_sorted_arrays(self, arr1, arr2):
        i = 0
        j = 0
        merged = []

        while i < len(arr1) and j < len(arr2):
            if arr1[i] <= arr2[j]:
                merged.append(arr1[i])
                i += 1
            else:
                merged.append(arr2[j])
                j += 1
        
        while i < len(arr1):
            merged.append(arr1[i])
            i += 1

        while j < len(arr2):
            merged.append(arr2[j])
            j += 1

        return merged


example_array_1 = [1, 2, 5, 8]
example_array_2 = [1, 3, 4, 7, 11]

example_solution_array = [1, 1, 2, 3, 4, 5, 7, 8, 11]
function_solution = MergeSortedSolution()
print(function_solution.merge_sorted_arrays(arr1=example_array_1, arr2=example_array_2))

[1, 1, 2, 3, 4, 5, 7, 8, 11]


In [21]:
# Example 4: 392. Is Subsequence.

# Given two strings s and t, return true if s is a subsequence of t, or false otherwise.

# A subsequence of a string is a sequence of characters that can be obtained by deleting some (or none) of the characters 
# from the original string, while maintaining the relative order of the remaining characters. 
# For example, "ace" is a subsequence of "abcde" while "aec" is not.

class SubSeqSolution:
    def is_subsequence(self, s, t):
        i = 0
        j = 0
        while i < len(s) and j < len(t):
            if s[i] == t[j]:
                i += 1
            else:
                j += 1

        if i == len(s):
            return True
            # If we incremented all the way through the subsequence, 
            # we've found a match for all the characters
        
        return False

example_sequence = "abcde"
example_subsequence = "ace"
example_nonsubsequence = "aec"

subseq_solution = SubSeqSolution()
print(subseq_solution.is_subsequence(s=example_subsequence, t=example_sequence))
print(subseq_solution.is_subsequence(s=example_nonsubsequence, t=example_sequence))


True
False


In [40]:
# Given an integer array nums sorted in non-decreasing order,
# return an array of the squares of each number sorted in non-decreasing order.

class SquaredSolution:
    def sortedSquares(self, nums):
        left = 0
        right = len(nums) - 1
        ans = []

        while left <= right:
            if abs(nums[left]) > abs(nums[right]):
                ans.append(nums[left]**2)
                left += 1
            else:
                ans.append(nums[right]**2)
                right -= 1

        ans.reverse()

        return ans
            

squared_input = [-4,-1,0,3,10]
squared_answer = [0,1,9,16,100]
squared_solution = SquaredSolution()
print(squared_solution.sortedSquares(nums=squared_input))

[0, 1, 9, 16, 100]


### Sliding windows

In [18]:
# Example 1: Given an array of positive integers nums and an integer k, 
# find the length of the longest subarray whose sum is less than or equal to k. 

class LongestArraySolution:
    def longest_array_leq_k(self, nums, k):
        left = 0
        current_sum = 0
        max_length = 0

        for right in range(0, len(nums)):

            current_sum = current_sum + nums[right]

            while current_sum > k and left < right:
                current_sum = current_sum - nums[left]
                left += 1
                
            current_length = 1 + right - left   # when left=right, window length is 1

            if current_length > max_length:
                max_length = current_length
        
        return max_length
    

# generate an array over which to take the sums
np.random.seed(0) 
random_integer_array = np.random.randint(1, 10, size=10) # Between 1 and 100 (inclusive)
maximum_sum = 10
longest_array_solution = LongestArraySolution()
print(random_integer_array)
print(longest_array_solution.longest_array_leq_k(nums=random_integer_array, k=maximum_sum))


[6 1 4 4 8 4 6 3 5 8]
3


In [14]:
# Example 2: You are given a binary string s (a string containing only "0" and "1"). 
# You may choose up to one "0" and flip it to a "1". 
# What is the length of the longest substring achievable that contains only "1"?

class BinaryStringSolution:
    def find_longest_substring(self, s):
        left = 0
        zero_counter = 0
        max_window_width = 0

        for right in range(len(s)):

            if s[right] == '0':
                zero_counter += 1

            while zero_counter > 1:
                left += 1              
                if s[left] == '0':
                    zero_counter -= 1
            
            window_width = 1 + right - left
            max_window_width = max(window_width, max_window_width)

        return max_window_width

example_string_input_1 = "1101100111"
binary_string_solution = BinaryStringSolution()
print(binary_string_solution.find_longest_substring(s=example_string_input_1)) # answer should be 5

example_string_input_2 = "110111"
print(binary_string_solution.find_longest_substring(s=example_string_input_2)) # answer should be 5


5
6


In [20]:
# Example 3: 713. Subarray Product Less Than K.

# Given an array of positive integers nums and an integer k, 
# return the number of subarrays where 
# the product of all the elements in the subarray is strictly less than k.

class ConstrainedProductSolution:
    def count_subarrays_product_less_than_k(self, nums, k):
        left = 0
        count = 0
        product = 1

        for right in range(len(nums)):
            product *= nums[right]

            while product >= k:
                product /= nums[left]
                left += 1

            count += 1 + right - left

        return count

constrained_product_solution = ConstrainedProductSolution()
    
example_nums = [10, 5, 2, 6]
example_k = 100
print(constrained_product_solution.count_subarrays_product_less_than_k(nums=example_nums, k=example_k))
# Answer = 8. The subarrays with products less than k are:
# [10], [5], [2], [6], [10, 5], [5, 2], [2, 6], [5, 2, 6]

8


In [29]:
# Example 4: Given an integer array nums and an integer k, 
# find the sum of the subarray with the largest sum whose length is k.

class SubarraySumSolution:
    def find_subarray_with_largest_sum(self, nums, k):
        
        sum_max_so_far = 0
        index_max_so_far = 0
        sum_current = sum(nums[0:(k-1)]) # initial values

        for i in range(0, len(nums)-k):

            sum_current += nums[i+k] - nums[i]

            if sum_current > sum_max_so_far:
               sum_max_so_far = sum_current
               i_max_so_far = i + 1

        largest_subarray = nums[i_max_so_far:(i_max_so_far + k)]

        return largest_subarray
    

example_nums = [1, 2, 3, 4, 5, 6]
example_k = 2
subarray_sum_solution = SubarraySumSolution()
print(subarray_sum_solution.find_subarray_with_largest_sum(nums=example_nums, k=example_k))

[5, 6]


In [38]:
# Example 2: 2270. Number of Ways to Split Array

# Given an integer array nums, 
# find the number of ways to split the array into two parts so that 
# the first section has a sum greater than or equal to the sum of the second section. 
# The second section should have at least one number.

class ArraySplitSolution:
    def count_splits_first_sum_larger_than_second(self, nums):
        array_count = 0
        left_sums = []
        right_sums = []
        left_sums.append(nums[0])

        for i in range(1, len(nums)): 
            # starts from -1 because must be at least one element in right array
            left_sums.append(left_sums[i-1] + nums[i])

        for i in range(0, len(nums) - 1):
            right_sums.append(left_sums[-1] - left_sums[i])
            if left_sums[i] > right_sums[i]:
                array_count += 1

        return array_count

example_nums = [1, 6, 3, 2, 7, 2]

array_split_solution = ArraySplitSolution()
print(array_split_solution.count_splits_first_sum_larger_than_second(nums=example_nums))

# NB: more efficient to start by calculating the total sum and incrementing the count within one loop


2


## Hashing

In [22]:
# Example 1: 1. Two Sum

# Given an array of integers nums and an integer target,
# return indices of two numbers such that they add up to target. 
# You cannot use the same index twice.

class TwoSumSolution:
    def find_indices_matching_sum(self, nums, target):
        hashmap = {}

        for i in range(len(nums)):
            if nums[i] not in hashmap.keys():
                hashmap[nums[i]] = [i]
            else:
                hashmap[nums[i]].append(i)

        for key1 in hashmap.keys():
            for key2 in reversed(hashmap.keys()):
                current_sum = key1 + key2
                if current_sum == target:
                    if key1 != key2:
                        return [hashmap[key1][0], hashmap[key2][0]]
                    else:
                        return hashmap[key1][:2]
                    
        print('no pairs match')


nums1 = [1, 1, 1, 1, 9]
nums2 = [1, 3, 5, 5, 6]
target = 10
print(TwoSumSolution().find_indices_matching_sum(nums1, target))
print(TwoSumSolution().find_indices_matching_sum(nums2, target))

# This can be made a lot faster by looking directly in the keys for [complement = target - current value]

[0, 4]
[2, 3]


In [24]:
# Example 2: 2351. First Letter to Appear Twice

# Given a string s, return the first character to appear twice. 
# It is guaranteed that the input will have a duplicate character.

class LetterTwiceSolution:
    def find_first_letter_appearing_twice(self, s):
        hashmap = {}
                    
        for char in s:
            if char not in hashmap.keys():
                hashmap[char] = 1
            else:
                return(char)


s = "abcdeab"
print(LetterTwiceSolution().find_first_letter_appearing_twice(s))

# value is True-False, so using set() is better

a


### Checking for existence

In [30]:
# Example 3: Given an integer array nums, 
# find all the unique numbers x in nums that satisfy the following: 
# x + 1 is not in nums, and x - 1 is not in nums.

class NoNeighboursSolution:
    def find_nums_without_neighbours(self, nums):
        uniques = set()
        
        for num in nums:
            if num not in uniques:
                uniques.add(num)

        satisfying = []

        for num in uniques:
            if not (num - 1 in uniques and num + 1 in uniques):
                satisfying.append(num)

        return satisfying


nums = [1, 3, 4, 5, 7]
print(NoNeighboursSolution().find_nums_without_neighbours(nums))

# No need for a loop to create the set; just use set(nums) directly

[1, 3, 5, 7]


## Linked lists

In [ ]:
# Linked list
def get_sum(head):
    ans = 0
    while head:
        ans += head.val
        head = head.next
    
    return ans

## Binary Trees

In [17]:
class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right
        
class Solution:
    """
    This class provides solutions for various problems related to binary trees.
    """
    
    def max_depth(self, root: Optional[TreeNode]) -> int:
        """
        Returns the maximum depth of a binary tree.
        
        Args:
            root: The root node of the binary tree.
        
        Returns:
            int: The maximum depth of the binary tree.
        """
        if not root:
            return 0
        
        left = self.max_depth(root.left)
        right = self.max_depth(root.right)
        return max(left, right) + 1
    
    def has_path_sum(self, root: Optional[TreeNode], target_sum: int) -> bool:
        """
        Determines if there exists a path from the root to a leaf in the binary tree
        such that the sum of the nodes on the path is equal to the target sum.
        
        Args:
            root: The root node of the binary tree.
            target_sum: The target sum to be achieved.
        
        Returns:
            bool: True if there exists a path with the target sum, False otherwise.
        """
        def dfs(node, curr):
            if not node:
                return False
            
            if node.left is None and node.right is None:
                return (curr + node.val) == target_sum
            
            curr += node.val
            left = dfs(node.left, curr)
            right = dfs(node.right, curr)
            return left or right
        
        return dfs(root, 0)
    

# Create the binary tree
root = TreeNode(val=5)
root.left = TreeNode(val=4, left=TreeNode(val=11, left=TreeNode(val=7), right=TreeNode(val=2)))
root.right = TreeNode(val=8, left=TreeNode(val=13), right=TreeNode(val=4, left=None, right=TreeNode(val=1)))

# Tree structure:
#         5
#        / \
#       4   8
#      /   / \
#     11  13  4
#    /  \      \
#   7    2      1

# Instantiate the Solution class
solution = Solution()

# Find the maximum depth of the tree
max_depth = solution.max_depth(root)
print(f"Maximum Depth of the Tree: {max_depth}")  # Output: Maximum Depth of the Tree

# Check if there's a path that sums to 7
path_exists = solution.has_path_sum(root, 7)
print(f"Path with sum 7 exists: {path_exists}")  # Output: True or False depending on the target sum and tree structure


Maximum Depth of the Tree: 4
Path with sum 7 exists: False


13

In [28]:
# Given the root of a binary tree, find the number of nodes that are good. 
# A node is good if the path between the root and the node has no nodes with a greater value.

class GoodNodesSolution:
    def count_good_nodes_in_tree(self, root: TreeNode):
        def count_good_nodes_in_subtree(node, max_val_of_ancestors):

            # Missing leaves don't contribute any good nodes
            if not node:
                return 0
            
            # How many good nodes do we get from the current node's children?
            max_val_incl_current_node = max(max_val_of_ancestors, node.val)
            good_nodes_from_left_child = count_good_nodes_in_subtree(node.left, max_val_incl_current_node)
            good_nodes_from_right_child = count_good_nodes_in_subtree(node.right, max_val_incl_current_node)
            good_nodes = good_nodes_from_left_child + good_nodes_from_right_child

            # Is our current node also a good node?
            if node.val >= max_val_of_ancestors:
                good_nodes += 1

            return good_nodes

        return count_good_nodes_in_subtree(node=root, max_val_of_ancestors=float("-inf"))
        # We start at the root, which has no ancestors 
        # It's the only node that doesn't need a "max_val_of_ancestors" to have been calculated externally
        # I.e. it's a good node by definition

good_nodes_solution = GoodNodesSolution()
good_nodes = good_nodes_solution.count_good_nodes_in_tree(root=root)
print(good_nodes)
    

4


In [40]:
# Given the roots of two binary trees p and q, check if they are the same tree. 
# Two binary trees are the same tree if they are structurally identical and the nodes have the same values.

root1 = copy.deepcopy(root)
root2 = copy.deepcopy(root)
root2.right.left.val = 2 # change one of the values so the trees don't match

class SameTreeSolution:
    def are_trees_identical(self, root1, root2):

        # Base cases where leaves are empty
        if root1 is None and root2 is None:
            return True
        if root1 is None and root2 is not None:
            return False
        if root2 is None and root1 is not None:
            return False
        
        # Check current node
        values_match = root1.val == root2.val

        # Check child nodes (recursive)
        left_children_match = self.are_trees_identical(root1=root1.left, root2=root2.left)
        right_children_match = self.are_trees_identical(root1=root1.right, root2=root2.right)

        # Combine
        is_complete_match = values_match and left_children_match and right_children_match

        return is_complete_match
    
same_tree_solution = SameTreeSolution()

are_trees_identical_1 = same_tree_solution.are_trees_identical(root1=root1, root2=root1)
print(are_trees_identical_1)

are_trees_identical_2 = same_tree_solution.are_trees_identical(root1=root1, root2=root2)
print(are_trees_identical_2)

True
False


## Graphs

In [1]:
import numpy as np

class GridWorld:
    def __init__(self, agent_position, goal_position):
        self.agent_position = agent_position
        self.goal_position = goal_position
        self.gridworld = np.zeros((4, 4))
    
    def print_environment(self):
        print(self.gridworld)
        print(f"Agent position: {self.agent_position}")
        print(f"Goal position: {self.goal_position}")

# Create an instance of GridWorld with specified agent and goal positions
agent_position = (0, 0)
goal_position = (3, 3)
gridworld_instance = GridWorld(agent_position, goal_position)

# Print the gridworld environment
gridworld_instance.print_environment()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Agent position: (0, 0)
Goal position: (3, 3)
