# Search algorithms 

Practice the fundamentals of:
* Search algorithms
* Graph algorithms
* Dynamic programming

In [2]:
# Import libraries
from typing import Optional

## Linked lists

In [ ]:
# Linked list
def get_sum(head):
    ans = 0
    while head:
        ans += head.val
        head = head.next
    
    return ans

## Binary Trees

In [7]:
class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right
        
class Solution:
    """
    This class provides solutions for various problems related to binary trees.
    """
    
    def maxDepth(self, root: Optional[TreeNode]) -> int:
        """
        Returns the maximum depth of a binary tree.
        
        Args:
            root: The root node of the binary tree.
        
        Returns:
            int: The maximum depth of the binary tree.
        """
        if not root:
            return 0
        
        left = self.maxDepth(root.left)
        right = self.maxDepth(root.right)
        return max(left, right) + 1
    
    def hasPathSum(self, root: Optional[TreeNode], targetSum: int) -> bool:
        """
        Determines if there exists a path from the root to a leaf in the binary tree
        such that the sum of the nodes on the path is equal to the target sum.
        
        Args:
            root: The root node of the binary tree.
            targetSum: The target sum to be achieved.
        
        Returns:
            bool: True if there exists a path with the target sum, False otherwise.
        """
        def dfs(node, curr):
            if not node:
                return False
            
            if node.left is None and node.right is None:
                return (curr + node.val) == targetSum
            
            curr += node.val
            left = dfs(node.left, curr)
            right = dfs(node.right, curr)
            return left or right
        
        return dfs(root, 0)
    

# Create the binary tree
root = TreeNode(5)
root.left = TreeNode(4, TreeNode(11, TreeNode(7), TreeNode(2)))
root.right = TreeNode(8, TreeNode(13), TreeNode(4, None, TreeNode(1)))

# Tree structure:
#         5
#        / \
#       4   8
#      /   / \
#     11  13  4
#    /  \      \
#   7    2      1

# Instantiate the Solution class
solution = Solution()

# Find the maximum depth of the tree
max_depth = solution.maxDepth(root)
print(f"Maximum Depth of the Tree: {max_depth}")  # Output: Maximum Depth of the Tree

# Check if there's a path that sums to 7
path_exists = solution.hasPathSum(root, 7)
print(f"Path with sum 7 exists: {path_exists}")  # Output: True or False depending on the target sum and tree structure


Maximum Depth of the Tree: 4


## Graphs

In [1]:
import numpy as np

class GridWorld:
    def __init__(self, agent_position, goal_position):
        self.agent_position = agent_position
        self.goal_position = goal_position
        self.gridworld = np.zeros((4, 4))
    
    def print_environment(self):
        print(self.gridworld)
        print(f"Agent position: {self.agent_position}")
        print(f"Goal position: {self.goal_position}")

# Create an instance of GridWorld with specified agent and goal positions
agent_position = (0, 0)
goal_position = (3, 3)
gridworld_instance = GridWorld(agent_position, goal_position)

# Print the gridworld environment
gridworld_instance.print_environment()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Agent position: (0, 0)
Goal position: (3, 3)
