# Search algorithms 

Practice the fundamentals of:
* Search algorithms
* Graph algorithms
* Dynamic programming

In [29]:
# Import libraries
from typing import Optional
import copy

## Linked lists

In [ ]:
# Linked list
def get_sum(head):
    ans = 0
    while head:
        ans += head.val
        head = head.next
    
    return ans

## Binary Trees

In [17]:
class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right
        
class Solution:
    """
    This class provides solutions for various problems related to binary trees.
    """
    
    def max_depth(self, root: Optional[TreeNode]) -> int:
        """
        Returns the maximum depth of a binary tree.
        
        Args:
            root: The root node of the binary tree.
        
        Returns:
            int: The maximum depth of the binary tree.
        """
        if not root:
            return 0
        
        left = self.max_depth(root.left)
        right = self.max_depth(root.right)
        return max(left, right) + 1
    
    def has_path_sum(self, root: Optional[TreeNode], target_sum: int) -> bool:
        """
        Determines if there exists a path from the root to a leaf in the binary tree
        such that the sum of the nodes on the path is equal to the target sum.
        
        Args:
            root: The root node of the binary tree.
            target_sum: The target sum to be achieved.
        
        Returns:
            bool: True if there exists a path with the target sum, False otherwise.
        """
        def dfs(node, curr):
            if not node:
                return False
            
            if node.left is None and node.right is None:
                return (curr + node.val) == target_sum
            
            curr += node.val
            left = dfs(node.left, curr)
            right = dfs(node.right, curr)
            return left or right
        
        return dfs(root, 0)
    

# Create the binary tree
root = TreeNode(val=5)
root.left = TreeNode(val=4, left=TreeNode(val=11, left=TreeNode(val=7), right=TreeNode(val=2)))
root.right = TreeNode(val=8, left=TreeNode(val=13), right=TreeNode(val=4, left=None, right=TreeNode(val=1)))

# Tree structure:
#         5
#        / \
#       4   8
#      /   / \
#     11  13  4
#    /  \      \
#   7    2      1

# Instantiate the Solution class
solution = Solution()

# Find the maximum depth of the tree
max_depth = solution.max_depth(root)
print(f"Maximum Depth of the Tree: {max_depth}")  # Output: Maximum Depth of the Tree

# Check if there's a path that sums to 7
path_exists = solution.has_path_sum(root, 7)
print(f"Path with sum 7 exists: {path_exists}")  # Output: True or False depending on the target sum and tree structure


Maximum Depth of the Tree: 4
Path with sum 7 exists: False


13

In [28]:
# Given the root of a binary tree, find the number of nodes that are good. 
# A node is good if the path between the root and the node has no nodes with a greater value.

class GoodNodesSolution:
    def count_good_nodes_in_tree(self, root: TreeNode):
        def count_good_nodes_in_subtree(node, max_val_of_ancestors):

            # Missing leaves don't contribute any good nodes
            if not node:
                return 0
            
            # How many good nodes do we get from the current node's children?
            max_val_incl_current_node = max(max_val_of_ancestors, node.val)
            good_nodes_from_left_child = count_good_nodes_in_subtree(node.left, max_val_incl_current_node)
            good_nodes_from_right_child = count_good_nodes_in_subtree(node.right, max_val_incl_current_node)
            good_nodes = good_nodes_from_left_child + good_nodes_from_right_child

            # Is our current node also a good node?
            if node.val >= max_val_of_ancestors:
                good_nodes += 1

            return good_nodes

        return count_good_nodes_in_subtree(node=root, max_val_of_ancestors=float("-inf"))
        # We start at the root, which has no ancestors 
        # It's the only node that doesn't need a "max_val_of_ancestors" to have been calculated externally
        # I.e. it's a good node by definition

good_nodes_solution = GoodNodesSolution()
good_nodes = good_nodes_solution.count_good_nodes_in_tree(root=root)
print(good_nodes)
    

4


In [40]:
# Given the roots of two binary trees p and q, check if they are the same tree. 
# Two binary trees are the same tree if they are structurally identical and the nodes have the same values.

root1 = copy.deepcopy(root)
root2 = copy.deepcopy(root)
root2.right.left.val = 2 # change one of the values so the trees don't match

class SameTreeSolution:
    def are_trees_identical(self, root1, root2):

        # Base cases where leaves are empty
        if root1 is None and root2 is None:
            return True
        if root1 is None and root2 is not None:
            return False
        if root2 is None and root1 is not None:
            return False
        
        # Check current node
        values_match = root1.val == root2.val

        # Check child nodes (recursive)
        left_children_match = self.are_trees_identical(root1=root1.left, root2=root2.left)
        right_children_match = self.are_trees_identical(root1=root1.right, root2=root2.right)

        # Combine
        is_complete_match = values_match and left_children_match and right_children_match

        return is_complete_match
    
same_tree_solution = SameTreeSolution()

are_trees_identical_1 = same_tree_solution.are_trees_identical(root1=root1, root2=root1)
print(are_trees_identical_1)

are_trees_identical_2 = same_tree_solution.are_trees_identical(root1=root1, root2=root2)
print(are_trees_identical_2)

True
False


## Graphs

In [1]:
import numpy as np

class GridWorld:
    def __init__(self, agent_position, goal_position):
        self.agent_position = agent_position
        self.goal_position = goal_position
        self.gridworld = np.zeros((4, 4))
    
    def print_environment(self):
        print(self.gridworld)
        print(f"Agent position: {self.agent_position}")
        print(f"Goal position: {self.goal_position}")

# Create an instance of GridWorld with specified agent and goal positions
agent_position = (0, 0)
goal_position = (3, 3)
gridworld_instance = GridWorld(agent_position, goal_position)

# Print the gridworld environment
gridworld_instance.print_environment()

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Agent position: (0, 0)
Goal position: (3, 3)
